/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_centaurean_clmax_schema_impl_PlatformsImpl */

#ifndef _Included_com_centaurean_clmax_schema_impl_PlatformsImpl
#define _Included_com_centaurean_clmax_schema_impl_PlatformsImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_serialVersionUID
#define com_centaurean_clmax_schema_impl_PlatformsImpl_serialVersionUID 1421746759512286392LL
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_ALTERNATIVE_HASHING_THRESHOLD_DEFAULT
#define com_centaurean_clmax_schema_impl_PlatformsImpl_ALTERNATIVE_HASHING_THRESHOLD_DEFAULT 2147483647L
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_MAX_ARRAY_SIZE
#define com_centaurean_clmax_schema_impl_PlatformsImpl_MAX_ARRAY_SIZE 2147483639L
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_KEYS
#define com_centaurean_clmax_schema_impl_PlatformsImpl_KEYS 0L
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_VALUES
#define com_centaurean_clmax_schema_impl_PlatformsImpl_VALUES 1L
#undef com_centaurean_clmax_schema_impl_PlatformsImpl_ENTRIES
#define com_centaurean_clmax_schema_impl_PlatformsImpl_ENTRIES 2L
/*
 * Class:     com_centaurean_clmax_schema_impl_PlatformsImpl
 * Method:    nativePlatforms
 * Signature: (Lcom/centaurean/clmax/schema/Platforms;)V
 */
JNIEXPORT void JNICALL Java_com_centaurean_clmax_schema_impl_PlatformsImpl_nativePlatforms
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
