/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_centaurean_clmax_schema_CLPlatforms */

#ifndef _Included_com_centaurean_clmax_schema_CLPlatforms
#define _Included_com_centaurean_clmax_schema_CLPlatforms
#ifdef __cplusplus
extern "C" {
#endif
#undef com_centaurean_clmax_schema_CLPlatforms_serialVersionUID
#define com_centaurean_clmax_schema_CLPlatforms_serialVersionUID 1421746759512286392LL
#undef com_centaurean_clmax_schema_CLPlatforms_ALTERNATIVE_HASHING_THRESHOLD_DEFAULT
#define com_centaurean_clmax_schema_CLPlatforms_ALTERNATIVE_HASHING_THRESHOLD_DEFAULT 2147483647L
#undef com_centaurean_clmax_schema_CLPlatforms_MAX_ARRAY_SIZE
#define com_centaurean_clmax_schema_CLPlatforms_MAX_ARRAY_SIZE 2147483639L
#undef com_centaurean_clmax_schema_CLPlatforms_KEYS
#define com_centaurean_clmax_schema_CLPlatforms_KEYS 0L
#undef com_centaurean_clmax_schema_CLPlatforms_VALUES
#define com_centaurean_clmax_schema_CLPlatforms_VALUES 1L
#undef com_centaurean_clmax_schema_CLPlatforms_ENTRIES
#define com_centaurean_clmax_schema_CLPlatforms_ENTRIES 2L
/*
 * Class:     com_centaurean_clmax_schema_CLPlatforms
 * Method:    getPlatforms
 * Signature: ()Lcom/centaurean/clmax/schema/CLPlatforms;
 */
JNIEXPORT jobject JNICALL Java_com_centaurean_clmax_schema_CLPlatforms_getPlatforms
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
